#lane_control/lane_controller_node
v_bar: 0.22
k_d: -3.5
k_theta: -1
k_Id: 1
k_Iphi: 0.0
theta_thres: 0.523
d_thres: 0.2615
d_offset: 0.0

# LP copying these into here for now since they are loaded from the lane_controller
#default parameters for dagu_car/wheels_driver_node 
use_rad_lim: False
min_rad: 0.06
wheel_distance: 0.103

velocity_to_m_per_s: 0.67
omega_to_rad_per_s: 4.75

use_ff_part: False
omega_ff: 0
omega_max: 999
omega_min: -999

integral_bounds:
  d:
    top: 0.3
    bot: -0.3
  phi:
    top: 1.2
    bot: -1.2

# TODO: from lane filter?
d_resolution: 0.011
phi_resolution: 0.051